### ISSUE TITLE
Contributor profile page width not correct in mobile.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#10]
Not sure if it's specific to mine. Unable to reproduce in desktop using firefox's responsive design mode.

Huawei Honor 8C
Chrome 101.0
Android 8.1.0

![Screenshot_20220529-000416](https://user-images.githubusercontent.com/25143503/170838645-0a015bee-585d-4e1e-bbe7-39701613d800.jpg)

**Comment by skks1212** [comment]
![image](https://user-images.githubusercontent.com/23238460/170844160-6bee6941-0379-43ed-b995-e4e976d78fd2.png)
Able to recreate on desktop. Error occurs due to no specification of break word for wrapping text.
