### ISSUE TITLE
Markdown content not being rendered as markdown html in short bio

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#133]
<img width="946" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/d015bf0b-ea99-4643-84b3-e59734ac0a26">

**Comment by AshrafMd-1** [comment]
@rithviknishad is this still an issue?
![image](https://github.com/coronasafe/leaderboard/assets/98876115/bc765709-145e-4588-a8a5-b0f7fbc44df7)

**Comment by rithviknishad** [comment]
Oh my bad, duplicate of #186 which was already completed
