### ISSUE TITLE
Feature: Image generation route to show skills badges

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#139]
### Feature Request

Add Image generation route to retrieve the skill badges of a user. These could be added to GitHub user's profile README or any other place.

### References:
- https://nextjs.org/docs/app/api-reference/functions/image-response
- https://www.youtube.com/watch?v=6rYzM_oWi7A

### Example

```
GET {{base_url}}/api/skillbadges/[slug].png?style=gallery
```

<img width="984" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/ef05c01b-bf98-4f7b-af59-8814d71343a2">

```
GET {{base_url}}/api/skillbadges/[slug].png?style=detailed
```

<img width="911" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/848bc744-3bc5-4650-95d4-87661c3bd71f">

**Comment by konavivekramakrishna** [comment]
I would like to work on it can you please assign me
