### ISSUE TITLE
Add git icons for events and contributor activity in event title

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#163]
<img width="72" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/5b72182f-ce0a-4bd9-a1d4-0c2186283a4c">

**Comment by dgparmar14** [comment]
I want take this task plese provide me this

**Comment by rhithesh** [comment]
@rithviknishad  how can I get  the icon links.

**Comment by rithviknishad** [comment]
We have react icons packaged being used in leaderboard.
Icons can be browsed from here: https://react-icons.github.io/react-icons/

**Comment by dgparmar14** [comment]
@rithviknishad can you please assign task to me?

**Comment by rithviknishad** [comment]
@dgparmar14 you are already assigned

**Comment by dgparmar14** [comment]
![Screenshot 2024-02-22 222010](https://github.com/coronasafe/leaderboard/assets/99136186/69e62de1-db42-4a52-9a6a-0f80c82e8c27)
Icons looks like this? right?

**Comment by rithviknishad** [comment]
Yup! Feel free to tweak the layout of a timeline node to make it represent in a cleaner way!

**Comment by dgparmar14** [comment]
I create one pull request for this issue can the mentor please review and if any changes are required please instruct me.

**Comment by rithviknishad** [comment]
Kindly link the PR with the issue. Refer: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
