### ISSUE TITLE
Truncate / exclude contributors that has 0 points in the weekly leaderboard page

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#171]
The weekly leaderboard page could grow uncontrollably big as more contributors come up.

### Tasks 
- [ ] Truncate / exclude contributors that have 0 points on the weekly leaderboard page. 

<img width="726" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/59606848-b86b-412c-b4e6-7bb10671f214">

**Comment by sagarkori143** [comment]
@rithviknishad Can you please assign it to me?

**Comment by sagarkori143** [comment]
@rithviknishad I'm having trouble in setting up the development environment. Getting this error after running npm run dev command.

![image](https://github.com/coronasafe/leaderboard/assets/129517558/4ce61fe2-3334-4033-ab73-81e671fcae09)

**Comment by rithviknishad** [comment]
run `./load-fixtures.sh` before npm run dev

**Comment by sagarkori143** [comment]
Still getting the same error on webpage and this on terminal:
![image](https://github.com/coronasafe/leaderboard/assets/129517558/0bb49189-4776-4ea0-8242-010aed4b89f8)

**Comment by rithviknishad** [comment]
did the fixtures get pulled? are there files inside `data-repo` folder?

**Comment by rithviknishad** [comment]
<img width="478" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/887ba210-cfcb-49a2-94ab-a6f211d6d688">

**Comment by sagarkori143** [comment]
NO.. here is nothing like data/data-repo

**Comment by rithviknishad** [comment]
Have a look at the `load-fixtures.sh` file. It simply creates a directory and clones the data repo inside it.

(I'm not 100% sure if it works on windows)

Can you try in WSL / Linux?

**Comment by sagarkori143** [comment]
Sorry, I currently don't have WSL/Linux set up.

**Comment by sagarkori143** [comment]
@rithviknishad What else can I do now?

**Comment by sagarkori143** [comment]
@rithviknishad  Friendly reminder.

**Comment by sagarkori143** [comment]
@rithviknishad It's a friendly reminder. Please suggest me a way so that I could set up the local development environment and start working on issues.

**Comment by rithviknishad** [comment]
@sagarkori143 unable to replicate the issue. WSL / Linux is preferred for development. Could you try setting up one and try again?

Attached screenshot where I tried doing `ls` before and after performing `./load-fixtures.sh`

<img width="1566" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/414e4451-26c7-4a47-9784-efcb6c5053ee">

**Comment by rithviknishad** [comment]
You could also try running the commands inside the `load-fixtures.sh` file manually/individually and figure out what exactly is not working.

**Comment by AshrafMd-1** [comment]
@sagarkori143 did it get fixed ??

also @rithviknishad  maybe we need to add the `load-fixtures.sh` inside the readme

**Comment by sagarkori143** [comment]
@AshrafMd-1 I genuinely want to work on this issue but I'm having problem in setting up the local dev environment. Could you help me with fixtures.sh problem?

**Comment by rithviknishad** [comment]
@AshrafMd-1 what's the other way?

Also @sagarkori143 were you able to figure out which part of the `load-fixtures.sh` was not working exactly?

@AshrafMd-1 let's update the README after clarifying this issue?

**Comment by AshrafMd-1** [comment]
@sagarkori143 so basically go to leaderboard-data repo and then download the repo as zip 

Unzip the file and there u will find data and contributions folder 

Delete these folders in the leaderboard repo and then move the data and contributions folder from leaderboard-data to main repo 

Cc @rithviknishad 

Also I don't know of it's the recent data but the whole program works

**Comment by AshrafMd-1** [comment]
First clone the leaderboard repo and delete the data and contributions folder 
![Screenshot_20231227-093842_GitHub.jpg](https://github.com/coronasafe/leaderboard/assets/98876115/aeb07bcc-cfa4-442d-aa81-a282b98bf87e)

Then download the leaderboard-data repo as zip 

![Screenshot_20231227-093805_GitHub.jpg](https://github.com/coronasafe/leaderboard/assets/98876115/b8666627-64b8-42f9-b489-12df8796ef8d)



And move the contributions and data folder from the leaderboard-Data to leaderboard folder 
![Screenshot_20231227-093815_GitHub.jpg](https://github.com/coronasafe/leaderboard/assets/98876115/30168167-5844-44b6-b7a3-24ba01d0c858)

**Comment by sagarkori143** [comment]
@AshrafMd-1 @rithviknishad  Thanks for helping me in setting up the local dev environment.
I have made changes to truncate the contributors list. But If were are filtering out on the basis of zero points then still there are a lot of people in the list because they have atleast 10 points they got for commenting. Either we should exclude on basis of points>15 else if eod_update, issue_opened, pr -(collaborated merged, opened, reviewed ) everything is zero. Pls give review regarding this and I will be raising the PR soon...

**Comment by sagarkori143** [comment]
@rithviknishad Please let me know about this. I want to make it by tonight. Thanks

**Comment by rithviknishad** [comment]
i understood, I've tried this a few days back. so instead of truncating based on points, we could truncate if all of the highlight specific metrics of that week is 0 (such as PRs opened, issues opened, etc...), instead of points
