### ISSUE TITLE
Migrate `Tooltip` jsx component to use CSS based tooltip to reduce client side javascript

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#175]
Currently `<Tooltip />` component is a component under `"use client"` and works using client-side javascript.

### Tasks

- [ ] Tooltip can be implemented without using javascript, use CSS instead.
- [ ] Remove `"use client"` directive since it no longer requires client interactivity (JS)

**Comment by AshrafMd-1** [comment]
@rithviknishad i want to work on this issue 
Can u assign me this issue.

**Comment by AshrafMd-1** [comment]
![Screenshot (408)](https://github.com/coronasafe/leaderboard/assets/98876115/602925ee-2553-46cb-a003-c929eed86f83)

@rithviknishad is this okay ?

**Comment by rithviknishad** [comment]
Tooltip going to the bottom of the cursor position would be ideally good!
