### ISSUE TITLE
Format "PR Collaborated" event's title

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#188]
<img width="682" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/556caa3c-93dc-49c8-b082-3b28208bfd5c">

**Comment by AshrafMd-1** [comment]
so what kind of look looks good ?

---

1. 
![image](https://github.com/coronasafe/leaderboard/assets/98876115/61b08aaa-9878-4f36-b423-bd3abccc2b7f)

---

2.
![image](https://github.com/coronasafe/leaderboard/assets/98876115/26b88597-4319-4261-8649-b6d7b3bdb39d)

**Comment by AshrafMd-1** [comment]
I want to work on this issue. Can you assign me this?

**Comment by rithviknishad** [comment]
> so what kind of look looks good ?
> 
> 
> ![image](https://private-user-images.githubusercontent.com/98876115/292912331-61b08aaa-9878-4f36-b423-bd3abccc2b7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDg5NDMsIm5iZiI6MTcwMzY0ODY0MywicGF0aCI6Ii85ODg3NjExNS8yOTI5MTIzMzEtNjFiMDhhYWEtOTg3OC00ZjM2LWI0MjMtYmQzYWJjY2MyYjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAzNDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZTIwMzZkOWE1MDI5YzMxMGRmYTJhZDM0NmRiZDJlYzIzMTI2Y2M2NGQzMTk2MjRhOTc5YTFkNzI5MGE3Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pX-PbCoVTAdoyFD1c3TFPRmrYPkERNgI0GPPrGNKJxE)
> 
> 
> ![image](https://private-user-images.githubusercontent.com/98876115/292912467-26b88597-4319-4261-8649-b6d7b3bdb39d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDg5NDMsIm5iZiI6MTcwMzY0ODY0MywicGF0aCI6Ii85ODg3NjExNS8yOTI5MTI0NjctMjZiODg1OTctNDMxOS00MjYxLTg2NDktYjZkN2IzYmRiMzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAzNDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NTdjNGEwMzJhOWFjNTNlYTU3ZWZjYjNhNjJmMTlkY2UyOGJkMDBiZmY2NzhiZmZkZDRhMWYyZTRhNGMwZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YDbZUvabOhmsUWDVmprNOTc5ZKl0tA9wrfYYHSp0kCo)

Instead how about this:

Title: Collaborated on a PR
Description: OpenGraph image of the PR

**Comment by AshrafMd-1** [comment]
@rithviknishad 
is the title and look okay ?
![image](https://github.com/coronasafe/leaderboard/assets/98876115/68193d44-bd56-48f5-b3e8-92e41ed5dd4f)

**Comment by rithviknishad** [comment]
Yup!
