### ISSUE TITLE
Last week highlights in contributor profile is not visible properly in light theme

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#189]
<img width="1089" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/a180aa1e-54d4-4f10-b616-e3bd32ebce31">

**Comment by sagarkori143** [comment]
@rithviknishad Is it about the labels like "in last 7 days" or "pull requests" ?

**Comment by rithviknishad** [comment]
My bad, forgot to mention that. It's about 

<number> in last 7 days

**Comment by sriharsh05** [comment]
@sagarkori143 are you working on this. 
If not @rithviknishad Please assign this to me.

**Comment by sagarkori143** [comment]
@sriharsh05 Yeah. You can take it.
