### ISSUE TITLE
Invalid URLs

### ISSUE THREAD

**Issue by konavivekramakrishna** [coronasafe/leaderboard#199]
visit https://contributors.ohc.network/contributors/Ashe

It is showing 500 Server Error

![image](https://github.com/coronasafe/leaderboard/assets/101407963/3b42922c-51b4-419d-b872-caa08641d6da)

visit https://contributors.ohc.network/dsfdsfdsf/Ashe

![image](https://github.com/coronasafe/leaderboard/assets/101407963/65b102fa-615d-4335-a559-c68095d9678d)

Expected behavior:

Handle All Invalid URLs with a redirect or Not Found page

cc : @rithviknishad

**Comment by konavivekramakrishna** [comment]
@rithviknishad 

can you please suggest the expected behavior for these urls
1. https://contributors.ohc.network/contributors/Ashe
2. https://contributors.ohc.network/dsfdsfdsf/Ashe

**Comment by rithviknishad** [comment]
Reference: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamicparams
