### ISSUE TITLE
Contributor's name is overflowing in the leaderboard

### ISSUE THREAD

**Issue by nihal467** [coronasafe/leaderboard#203]
**Description**

When the contributor has a lengthy name like "Konavivekramakrishna" , the text overflows in the leaderboard

**Screenshot of the bug**

![image](https://github.com/coronasafe/leaderboard/assets/57055998/1dc221ab-2e8f-45d0-9c04-a0cebf33b373)

**Comment by corners2wall** [comment]
@rithviknishad, Assign to me

**Comment by corners2wall** [comment]
@rithviknishad  check please
