### ISSUE TITLE
Leaderboard is not auto-refreshing contributors data

### ISSUE THREAD

**Issue by nihal467** [coronasafe/leaderboard#204]
**Description**

The leaderboard is not auto-refreshing the data on the individual contributor's page.

**Screenshot**

![image](https://github.com/coronasafe/leaderboard/assets/57055998/c290f52d-f003-466c-8c03-b29da89f41eb)

**Comment by rithviknishad** [comment]
@nihal467 this should be fixed now. The https://github.com/coronasafe/leaderboard-data was not configured properly for vercel deployments. It has now been configured and contributors.ohc.network should now show the daily updated page.
