### ISSUE TITLE
Multi-select filter for leaderboard contributors role

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#231]
Add a role multi-select filter to the leaderboard filters.

The following choices to be present:

- Open Source Contributor (if `core == intern == operations == false`)
- Core Team (if `core == true`)
- Intern (if `intern == true`)
- Operations (if `operations == true`)

<img width="1454" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/41444fe7-c7a7-4821-9202-4adb84f1a131">

<img width="511" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/d6d37c46-b392-4b2a-9abc-e63faa709efe">

**Comment by UdaySagar-Git** [comment]
I want to work on this issue , can you please assign me !
