### ISSUE TITLE
Show recent release events in a seperate section

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#233]
Add a releases section in the leaderboard home page, which will list the recent 10 releases made in the organization across all repositories.

**Comment by kirtanchandak** [comment]
Hey, I can give this issue a try! Can you give me the approach to how can I start?

**Comment by rithviknishad** [comment]
You could create a server component that makes a graphql call to fetch all the release events happening in for the configured GitHub organization (this is configured in the env).

This component could be shown in the home page.

**Comment by kirtanchandak** [comment]
https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#get-an-organization - I went through this documentation but there is no specific mention of releases of an organization 

But I tried to fetch the specific repositories releases and I am getting a 200OK - 

![image](https://github.com/coronasafe/leaderboard/assets/92196705/bc057fb1-8c05-4d8f-863d-7cefdbcf117d)

thoughts?

**Comment by rithviknishad** [comment]
AFAIK, there is no REST API to list releases at an organization level and only available at repository level.

You could instead use the GraphQL endpoint to fetch the recent releases of the recent repositories of the org.

**Comment by kirtanchandak** [comment]
hey i've fetched the latest 10 releases form graphql API endpoint, do you have any specific design idea for the section that is to be added in the home page?

**Comment by rithviknishad** [comment]
Feel free to come up with your own design 😄
