### ISSUE TITLE
Home page user's profile card limitation

### ISSUE THREAD

**Issue by dgparmar14** [coronasafe/leaderboard#237]
## Issue Description
On the home page there is in the "Our Contributors" section all user's profile cards are shown creates an infinite scroll(too long scrolling) and it may take a long time to render the home page as well so need to add limitations on it 

## Expected Behavior
6 to 9 users are shown on home page all others on people's page.

## Actual Behavior
All the user's profile card on home page

**Comment by dgparmar14** [comment]
Could you please assign this issue to me i want to fix this.

**Comment by rithviknishad** [comment]
That'd be nice!

**Comment by rithviknishad** [comment]
Do drop a screenshot of the page size before and after

**Comment by dgparmar14** [comment]
### Before: It fetches all the contributors it will take too much time to load home page.
![Screenshot 2024-02-24 224934](https://github.com/coronasafe/leaderboard/assets/99136186/63c90217-a45a-4dda-83da-d175d344879d)

### After: Now it will take only 8 contributors' profile info 
![image](https://github.com/coronasafe/leaderboard/assets/99136186/e7942138-2f0f-4630-9e19-774577e1a1ea)

@rithviknishad

**Comment by rithviknishad** [comment]
By page size I meant the bytes the size of the `/` routes html

**Comment by rithviknishad** [comment]
<img width="525" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/f7fed4c2-3357-465d-af00-e335dcea25b0">

**Comment by dgparmar14** [comment]
### Before: it takes 81.5kb Resource size 2.3 MB
![Screenshot 2024-02-24 231113](https://github.com/coronasafe/leaderboard/assets/99136186/1011c28c-73db-4216-ba2f-8895c357ae15)

### After: It takes 15.5kb and Resource size is 130kb
![image](https://github.com/coronasafe/leaderboard/assets/99136186/402dccb0-e0af-4c3e-aabd-b6b07bd449b4)

**Comment by rithviknishad** [comment]
Awesome 🚀
