### ISSUE TITLE
Feed: Event title is not responsive 

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#238]
<img width="987" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/31f8279f-7a05-45a2-9622-c316f9a4f799">

**Comment by dgparmar14** [comment]
Okk i will resolve it i want take this

**Comment by dgparmar14** [comment]
@gsoc @rithviknishad 
![image](https://github.com/coronasafe/leaderboard/assets/99136186/28c46e68-3edb-41a7-96a2-3aa1d7364bde)

See this is looks good?

and i have one idea that on mobile size only icons showen and event name will be removed

**Comment by rithviknishad** [comment]
The normal view looks good!

For the mobile view, I don't think icons alone would be readable. We could hide the org name. and make the relative time text smaller. it feels larger than the title

**Comment by dgparmar14** [comment]
@rithviknishad  Sure, I will do it

**Comment by dgparmar14** [comment]
@rithviknishad Yup,there is a space so I will do it
