### ISSUE TITLE
Content overflowing from the edges of the window on certain screen resolutions

### ISSUE THREAD

**Issue by alanansari** [coronasafe/leaderboard#239]
**Describe the bug**
The issue is of responsiveness on some window sizes.
The content of the homepage goes beyond the edges of the screen on the x-axis.
Usually ocurring on screens with width of 1280

**To Reproduce**

1. Go to https://contributors.ohc.network/
2. Right click and go to inspect
3. Press ctrl + shift + m to toggle device toolbar
4. Set screen resultion width 1280
5. See error

**Expected behavior**
Padding from the edges of the browser in these particular resolutions.

**Screenshots**
<img width="960" alt="image" src="https://github.com/coronasafe/leaderboard/assets/22475370/a3abf271-f89a-4b35-9e3a-3dfffe0c08ca">

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 122.0.6261.70 (Official Build) (64-bit)
- Screen Resolution: 1280 x 720
- Browser Viewport: 1280 x 585 (browser viewport window's size without taskbars/toolbars/address bars)

**Comment by JoshuaOloton** [comment]
Hello. Please assign this issue to me

**Comment by rash-27** [comment]
I would like to work on this issue
