### ISSUE TITLE
Using a third party fetcher such as tanstack query in `/feed` route and fix crashing of that page in 4th page

### ISSUE THREAD

**Issue by Re-Dei** [coronasafe/leaderboard#248]
## Description
Currently, the /feed page is using useEffect with fetch which is not recommeded by React itself. It says to use a third party fetcher such as Tanstack Query or SWR to fetch data on the client side. The other problem is that due to unauthorized API that is current in use, the feed crashes in the 4th page with error code 429.

## Solution
- Create a Next.js API use the authorized token, however this api is public so rate limit this API so that it cannot be spammed
- Use third party fetchers to replace the useEffect with fetch
- Both the API and the fetcher should be able to paginate the data (Tip: useInfiniteQuery of tanstack query can be useful)
- Extra: make the top page i.e. the page.tsx in /feed server side (remove "use client") to utilize the speediness of SSR because SSR>CSR. So that the page loads quickly

## Willing to solve issue or working on it?
Maybe but not right now. Up for grabs for anyone who is willing to.

**Comment by dgparmar14** [comment]
@rithviknishad 
I already think this and occur same problem and
I think there is no need to use a third party. We can add a pagination feature that will fetch only the necessary feed data to load at a time. and it makes good UX and we can add filters to the filter-out feed data for forked or push or comment etc.

**Comment by Re-Dei** [comment]
Here, i think the problem is the public api that is being used to fetch the data. Since it is unauthorized the app can only fetch a certain amount of data before reaching the limit and return the unauthorized error and crashing on the 4th page. I think I have found a way to solve this issue and will be working on it soon after I am done writing my gsoc proposals.

**Comment by rithviknishad** [comment]
@Re-Dei just clarifying, this issue is not a GSoC project.

**Comment by Re-Dei** [comment]
Can anyone assign me this issue?

**Comment by dgparmar14** [comment]
@rithviknishad This issue is solved in my previous PR #314.

**Comment by rithviknishad** [comment]
Closing as completed in #314
