### ISSUE TITLE
Support for Personalizing the Leaderboard colors

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#249]
Currently, although any organization could deploy it for their organization, we are not able to configure org. specific colors for the leaderboard.

We have a primary color palette that is used by us, but a different organization may need a different color palette to be used as the primary color to suit their needs.

<img width="400" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/49257415-5561-455d-962d-d29129bff309">

---

Suggest potential solutions on how to make this configurable so that various organizations can deploy leaderboards with their branding colors.

**Tips:**

- Organization-specific data sits in the data repository and not in this repository. 
https://github.com/coronasafe/leaderboard-data

**Comment by dgparmar14** [comment]
@rithviknishad  I like to implement this new exciting feature.

**Comment by dgparmar14** [comment]
### Themes suggestion:

**Techy Blue Theme:**
Primary Accent Color: #0366d6 (Blue)
Secondary Accent Color: #24292e (Dark Gray)
Neutral Color: #f6f8fa (Light Gray)
Text Color: #24292e (Dark Gray)

**Data-driven Green Theme:**
Primary Accent Color: #28a745 (Green)
Secondary Accent Color: #6cb2eb (Light Blue)
Neutral Color: #f8f9fa (Off-White)
Text Color: #333333 (Dark Gray)

**Code-friendly Dark Theme:**
Primary Accent Color: #6f42c1 (Purple)
Secondary Accent Color: #586069 (Gray)
Neutral Color: #1e1e1e (Dark Gray)
Text Color: #e1e4e8 (Light Gray)

**Corporate Navy Theme:**
Primary Accent Color: #0366d6 (Navy Blue)
Secondary Accent Color: #586069 (Gray)
Neutral Color: #f6f8fa (Light Gray)
Text Color: #24292e (Dark Gray)

**Minimalistic Monochrome Theme:**
Primary Accent Color: #333333 (Dark Gray)
Secondary Accent Color: #666666 (Medium Gray)
Neutral Color: #f8f9fa (Off-White)
Text Color: #24292e (Dark Gray)

@rithviknishad Hey, I think it is the best theme .5 themes are good number ?

**Comment by rithviknishad** [comment]
@dgparmar14 Let's make it in such a way that organization can set their color palette instead of choosing from a pre-defined theme.

**Comment by dgparmar14** [comment]
@rithviknishad Okay, I think  One way to achieve this is by providing a user interface where organizations can input their custom color values.

**Comment by rithviknishad** [comment]
We could add a user interface for configuring various environments along with this at a later stage. Let's keep it simple now assuming the one deploying and configuring this is an engineer.

**Comment by dgparmar14** [comment]
Okay, you are trying to say that,  rather than creating a GUI for setting up custom color palettes, the system could rely on configuration files or environment variables that the engineer can modify directly. right?

**Comment by rithviknishad** [comment]
We could build a GUI to configure/generate environment variables as an easy step for devs, but that's a separate issue of its own.

**Comment by dgparmar14** [comment]
Okay as per my understanding on this Idea ,

### env file 

NEXT_PUBLIC_CUSTOM_BLUE=#4C8BF5
NEXT_PUBLIC_CUSTOM_RED=#F87171
NEXT_PUBLIC_CUSTOM_GREEN=#34D399

### tailwind configuration file
module.exports = {
  theme: {
    extend: {
      colors: {
        customBlue: process.env.NEXT_PUBLIC_CUSTOM_BLUE,
        customRed: process.env.NEXT_PUBLIC_CUSTOM_RED,
        customGreen: process.env.NEXT_PUBLIC_CUSTOM_GREEN,
        // Add more custom colors as needed
      },
    },
  },
};

It is just an example how I understand and how can we do it .Is it right approach?
@rithviknishad

**Comment by dgparmar14** [comment]
We can implant this using configuration file also 

{
  "customBlue": "#4C8BF5",
  "customRed": "#F87171",
  "customGreen": "#34D399"
}

const customColors = require('./customColors.json');

module.exports = {
  theme: {
    extend: {
      colors: {
        ...customColors,
      },
    },
  },
};

**Comment by rithviknishad** [comment]
Wouldn't it be much simpler to just keep the `tailwind.config.js` inside the data-repo itself and symlink it here?

**Comment by dgparmar14** [comment]
Okay it is great to move tailwind.config file ,
But i have one more idea ,  we add theme folder in leaderboard data repo and create there files like theme1.json 
theme2.json theme3.json .?

**Comment by rithviknishad** [comment]
And to allow the page visitor to select a theme?

**Comment by dgparmar14** [comment]
Yes  it's almost like that approach, 
let me give you clear view
one org try to use our leadrboard tool
they add their json file for their preferred 2 or 3 themes and we can add that themes selection foe that in our page.

**Comment by rithviknishad** [comment]
Nice idea, we can do those as enhancements as separate issues. Let's get this out while keeping it as simple as possible for the first version.

**Comment by dgparmar14** [comment]
Okay, So final decision is to move t.config file in data repo file . what if for future flexibility create there theme folder

**Comment by dgparmar14** [comment]
@rithviknishad for the updation script 

can I go for a change in load-fixtures.sh or create a new one?

: "${FIXTURES_SOURCE:=https://github.com/coronasafe/leaderboard-data.git}"

rm -rf data-repo
mkdir data-repo
cd data-repo

git init
git remote add --mirror=fetch origin ${FIXTURES_SOURCE}
git config core.sparseCheckout true

echo "data/" >> .git/info/sparse-checkout
echo "contributors/" >> .git/info/sparse-checkout
echo "tailwind.config.js" >> .git/info/sparse-checkout

git pull origin main

**Comment by rithviknishad** [comment]
Update the `load-fixtures.sh` itself. Let's also rename the `load-fixtures.sh` to `load-org-data.sh` as that'd be more appropriate going forward
