### ISSUE TITLE
clicking on commit link on  /feed. redirects to github api page

### ISSUE THREAD

**Issue by rhithesh** [coronasafe/leaderboard#265]
<img width="1431" alt="Screenshot 2024-02-27 at 7 59 59 PM" src="https://github.com/coronasafe/leaderboard/assets/115660976/a5bfbcd3-dd6a-467e-94f9-d7eb5eff0f30">
<img width="1431" alt="Screenshot 2024-02-27 at 8 00 08 PM" src="https://github.com/coronasafe/leaderboard/assets/115660976/aa066064-d677-4fda-94bc-daf5ca36248d">
I would like to work on this issue

**Comment by rithviknishad** [comment]
@rhithesh any updates on this?

**Comment by manu-r12** [comment]
This seems interesting, would love to tackle this one ✨🚀

**Comment by manu-r12** [comment]
Hey @rithviknishad 
i think i have seem to have made some progress with this issue. However, i want you take a look to identify that, **is it how this link should work?**

Here is the cljp

https://github.com/coronasafe/leaderboard/assets/78516177/b456bb3f-b31f-4efb-9de6-1b5099387c84

**Comment by rithviknishad** [comment]
No, clicking on a commit should take you to the commit's `html_url` as we get from the github APIs

**Comment by manu-r12** [comment]
**Is this the expected behavior.?**
if not, a little descriptive hint would be so helpful
thanks agian

here is the clip

https://github.com/coronasafe/leaderboard/assets/78516177/08ebd92f-bf7b-48ac-87a7-fd670378ab77

**Comment by rithviknishad** [comment]
Yup! Expected behaviour!
