### ISSUE TITLE
Changing the UI of Dark/Light Mode Button to a more interactive and modern UI

### ISSUE THREAD

**Issue by Lobi29** [coronasafe/leaderboard#268]
- I wanted to change the dark/light mode button of Leader Dashboard to a more interactive and modern UI.

<h1 align="center">
Sample Design
</h1>

- dark mode 

![dark](https://github.com/coronasafe/leaderboard/assets/108052802/a169f170-6b47-4c9a-a334-3844edc30847)

- light mode

![light](https://github.com/coronasafe/leaderboard/assets/108052802/ba0070ba-2a58-4c80-ba03-5208da8c6595)

**Comment by rithviknishad** [comment]
Closing as completed in ab428212639427fe3da8f6cb32225d0be99d68fe
