### ISSUE TITLE
Change the UI of the Navbar to a more modern and interactive navbar

### ISSUE THREAD

**Issue by Lobi29** [coronasafe/leaderboard#278]
![leaderboard](https://github.com/coronasafe/leaderboard/assets/108052802/ee91839a-e125-4238-95d1-a0e5462599a7)

<h3 align="center">I wanted to propose some enhancements to our Navbar that would make it more modern, interactive, and aesthetically pleasing. Here are the key features and improvements I suggest:</h1>

### Contribute Now Option
1. Introduce a prominent "Contribute Now" option within the Navbar, providing users with a clear call-to-action to encourage engagement and support for our platform's goals.

### Decreasing Navbar Height
2. Currently, the Navbar's height appears bulky and may not align with modern design trends. I propose reducing the height to a more modest and visually appealing size, ensuring it integrates seamlessly with the overall website layout.

### Animated Border Middle Div
3. Implement animation effects for the middle div of the Navbar's border to add dynamism and interactivity. This subtle animation will enhance user engagement and create a more polished user interface.

### Transparent and Sticky Navbar:
4. Transform the Navbar to be transparent and sticky, allowing it to remain visible at the top of the page while users scroll through content. This design approach not only offers a sleek and modern appearance but also ensures easy access to navigation options throughout the browsing experience.

**Comment by HARSHDOIPHODE** [comment]
Can anyone assign me this issue?
