### ISSUE TITLE
Enhance Scrollbar Design for Improved User Experience

### ISSUE THREAD

**Issue by Lobi29** [coronasafe/leaderboard#279]
### Description:
- The scrollbar is an essential UI element that greatly influences the user experience while navigating through content-rich applications and websites. 
- my aims is to enhance the scrollbar design to improve usability, aesthetics, and user engagement across our platform.

**Comment by rithviknishad** [comment]
Could you explain how you are intending to enhance the scrollbar design?

**Comment by Lobi29** [comment]
Simply adding a touch of padding and width to --webkit-thumb, while imbuing it with a dynamic color theme that seamlessly adjusts to the currently active theme of the site 👍

**Comment by rithviknishad** [comment]
https://github.com/coronasafe/leaderboard/pull/305#issuecomment-2029084679
