### ISSUE TITLE
Improve mobile responsiveness of Contributors page

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#288]
![image](https://github.com/coronasafe/leaderboard/assets/25143503/12b188cd-4c19-4a54-9f4d-4c6caf424210)

**Comment by Lobi29** [comment]
@rithviknishad I am pleased to tackle this issue. Please assign it to me 🙏

**Comment by UdaySagar-Git** [comment]
hi @rithviknishad https://github.com/coronasafe/leaderboard/pull/282 could have fixed it 

@Lobi29 you can modify if it can be further improved
