### ISSUE TITLE
Client side exception in feed page 

### ISSUE THREAD

**Issue by dgparmar14** [coronasafe/leaderboard#292]
### Description :
I noticed that if we go on feed page and go down and click on more 3 times it will show a client-side expectations occur. 
![image-1](https://github.com/coronasafe/leaderboard/assets/99136186/d5dd533b-b902-47e8-a520-d288af45f669)

**Comment by dgparmar14** [comment]
@rithviknishad Hey, rithvik I want to take this issue

**Comment by Re-Dei** [comment]
This issue is linked with issue #248. I have been researching different ways to solve this issue and found that it cause by unauthorized access to the github's api.

**Comment by dgparmar14** [comment]
Me and Rithvik already discussed this issue and we reached a solution, Implementation in progress
