### ISSUE TITLE
Support for custom date range filter in Contributor Activity

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#294]
Currently, the contributor activity date filter can only view data ranging at most a month.

To allow use cases to show activity from any date and range, change to a dynamic date range filter like how we have in `/leaderboard` page

<img width="1441" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/981d8cbc-c4ff-4be8-aab7-38567ce8ac39">

<img width="1205" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/7fda7bad-91eb-4f83-9e2a-504a51015f2e">

**Comment by Lobi29** [comment]
Given my prior experience working on the contribution activity section's filter 🛠️, I believe I'm well-equipped to tackle this particular issue. Would you kindly assign it to me?😊

**Comment by rithviknishad** [comment]
@Lobi29 There are 4 other issues assigned to you that have no linked PRs yet. It'd be great if you could close the other issues before taking up new ones 😄

https://github.com/coronasafe/leaderboard/issues?q=assignee%3ALobi29+is%3Aopen

**Comment by Lobi29** [comment]
@rithviknishad Following your earlier guidance, I've implemented the recommendations to the best of my ability. You can now explore all four pull requests, each representing a step towards refining our project's design and functionality. 😊👍

**Comment by rithviknishad** [comment]
Kindly link the PRs with a closing tag :) 
Refer: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by Ayush398** [comment]
can you please  assign me this issue

**Comment by Samuel-Aktar-Laskar** [comment]
@rithviknishad Can you please assign this issue to me? 
I started working on it and hopefully get it done by tomorrow.
