### ISSUE TITLE
Show rank of contributor inside the contributor profile page

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#295]
<img width="1973" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/8a0b133d-3323-41a0-b0c7-49fd63cad28d">

<img width="842" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/4b6af3f7-52ea-4009-915d-36779f98cbaf">

**Comment by dgparmar14** [comment]
@rithviknishad  
I want to work up on this

**Comment by dgparmar14** [comment]
@rithviknishad What type of rank like? On a weekly basis ?

**Comment by dgparmar14** [comment]
![image](https://github.com/coronasafe/leaderboard/assets/99136186/8410b7f5-5b5a-4d60-962f-7650ff78685e)
Is this looks good?

**Comment by rithviknishad** [comment]
How about something like this? Try to make it look awesome! It is a page where you can showcase/show-off to other places about your activity at OHC

<img width="1479" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/2dedcdcc-bde0-4bdd-9e96-8a7508515d7f">

**Comment by rithviknishad** [comment]
Yup, let's take it from the `weekSummary`.

**Comment by rithviknishad** [comment]
Also add the circular shadow animation in the contributors profile if their rank is 1/2/3.

**Comment by dgparmar14** [comment]
![Screenshot 2024-03-02 223442](https://github.com/coronasafe/leaderboard/assets/99136186/5c5774d7-d7ef-474e-aa09-5379b53fc8b8)
![Screenshot 2024-03-02 224311](https://github.com/coronasafe/leaderboard/assets/99136186/d788d8a7-8116-4d20-979a-2acce701a05e)
![image](https://github.com/coronasafe/leaderboard/assets/99136186/3a048b41-2187-4554-8393-a840e2e93ca8)


Which one looks better?
