### ISSUE TITLE
UI improvements to Contributor Badge Popup

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#298]
- [ ] The badge popup needs to have a visual separation from the background and the popup. 
Maybe add a border or separation or change in bg-color to create a visual separation.

- [ ] Show green for badge levels only if that level was attained. Unobtained levels to remain gray / faded out.

<img width="1119" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/714a9d95-10e1-4c57-8078-6d818326a437">

**Comment by Ayush398** [comment]
Please assign me this issue
