### ISSUE TITLE
Incorrect rank display upon search 

### ISSUE THREAD

**Issue by UdaySagar-Git** [coronasafe/leaderboard#311]
Currently, the rank gets updated upon searching in the leaderboard page. However, the intended behavior is that the rank should not be updated upon search, and it should display the rank based on the applied filters.

before search: 
![image](https://github.com/coronasafe/leaderboard/assets/111575806/e9a0fd8c-8d6e-4bcf-839e-8b39351d1ebd)
after search:
![image](https://github.com/coronasafe/leaderboard/assets/111575806/559f63aa-7cc5-42e7-a87f-521313721be9)

**Comment by UdaySagar-Git** [comment]
can you please assign me 

and just a question , should ordering affect the ranks ?
for example , changing sort order from desc to asc should change the 1st place to the last or 
keep the 1st place as first and just display last rank in the first

**Comment by rithviknishad** [comment]
@UdaySagar-Git nope, ordering should not affect ranks. If order is reversed, last item should have rank 1
