### ISSUE TITLE
Specify a max-width for the navbar

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#316]
Currently, the nav bar does not look good in desktop view as it uses the entire width.

### Before
<img width="3006" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/70693094-98e4-4b64-933f-fc1661c02c68">

### After

`max-w-8xl mx-auto px-2 lg:px-4`

<img width="2488" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/dce79408-9622-495a-8eac-00cd58320d7a">

**Comment by Ayush398** [comment]
Can you please assign me this issue

**Comment by rithviknishad** [comment]
Completed in 0d5784d3ee09f03419316f3da7b946f7f35f5a90
