### ISSUE TITLE
Bottom Border of Navbar is not sticky

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#319]
<img width="1709" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/3e784542-7213-4946-b647-eae9b2abb44a">

<img width="1694" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/09af08b1-3233-4be6-b83d-ddc105d7f0e5">

**Comment by Ashutosh0602** [comment]
I would to like to work this issue, please assign me
