### ISSUE TITLE
Multiple duplicate review events captured by scraper

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#324]
The scraper seems to be capturing multiple review events (duplicate) in some cases. (Review events are unique by their PR Review ID (the last number in the link).

### Tasks

- [ ] Update the scraper to register duplicate review events. (Skip appending if the URL is already present in the list of activities).
- [ ] Create a script to clean existing data by removing duplicate events.

<img width="1238" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/70dc4671-1a1e-4aff-a805-ba945f57a821">

**Comment by UdaySagar-Git** [comment]
can you please assign me !

**Comment by Ayush398** [comment]
Can you please assign me this issue
