### ISSUE TITLE
Show organization "weeks from start" in home page

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#327]
### Action Items

- [ ] Create an env `NEXT_PUBLIC_ORG_START_DATE`
- [ ] Show weeks since the configured start date on home page
- [ ] On hover, show days since start date and maybe the org start date itself as tooltip

**Comment by dgparmar14** [comment]
I want take this issue can you please assign me.

**Comment by dgparmar14** [comment]
@rithviknishad  Could you please provide the starting date of CoronaSafe?

**Comment by rithviknishad** [comment]
Put a dummy date for now, let's update the env just before merge.

**Comment by dgparmar14** [comment]
![image](https://github.com/coronasafe/leaderboard/assets/99136186/72081a54-65c1-4667-8f94-ed0504af971e)

Is it something like this?

**Comment by rithviknishad** [comment]
Let's not clutter the nav bar. This can be shown in home page alone.

**Comment by rithviknishad** [comment]
We could maybe show it below what we do section

**Comment by dgparmar14** [comment]
@rithviknishad 
![image](https://github.com/coronasafe/leaderboard/assets/99136186/729f55f2-94f5-40ae-b75c-2031124710aa)
Is it something like this?

**Comment by dgparmar14** [comment]
@rithviknishad Is it fine or any changes in desgin or position?

**Comment by dgparmar14** [comment]
> This doesn't seem to be right... Can you think of some other way that we could represent this better?

Yes, I also think this, Currently i am not asking about the design i only need confirmation of it's position .
Is it right in the miidel of both or it should be close to uper side or below?

**Comment by rithviknishad** [comment]
How about on top of the top 5 contributors section?

**Comment by dgparmar14** [comment]
> How about on top of the top 5 contributors section?

I have similiar idea in leaderboard component we have text `last 7 days` instead of this can week do something like this?
![image](https://github.com/coronasafe/leaderboard/assets/99136186/473f79f8-dcd8-4cfa-aca6-ebd037837720)

**Comment by rithviknishad** [comment]
Yup! We could drop the word "ongoing" maybe. Also on hover let's show the actual date.

**Comment by dgparmar14** [comment]
> Yup! We could drop the word "ongoing" maybe. Also on hover let's show the actual date.

Okk So, i will do it like `week 24` and in tooltip we can show starting date `since 1-1-2024` or only date `1-1-2024` or any suggestion by you?
And for tooltip can i use nextui/tooltip? [https://nextui.org/docs/components/tooltip](url)
Or go with react-tooltip?

**Comment by dgparmar14** [comment]
![image](https://github.com/coronasafe/leaderboard/assets/99136186/59bcc749-c435-4868-a23f-ef3e4b8a100c)

**Comment by rithviknishad** [comment]
LGTM
