### ISSUE TITLE
Optimize `load-org-data.sh` script to skip cloning if already cloned

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#334]
### Problem

When we run `./load-org-data.sh` the script deletes existing data repo and clones it altogether again. This could take some time as lots of data is being fetched. Instead if already cloned, we could save time by only pulling the latest changes from the data repo.

### Action Items

- [ ] Update `load-org-data.sh` script to avoid cloning the repository again if already cloned once.
- [ ] Ensure local changes inside `data-repo` are discarded when `load-org-data.sh` is called again. (`git checkout .`)

<img width="778" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/d3e8c4a7-50be-4bcc-82fb-314711e41496">

**Comment by UdaySagar-Git** [comment]
can you please assign me this
