### ISSUE TITLE
Badges overflowing and shadows being clipped in mobile view

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#344]
<img width="427" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/69c324ca-0ec8-43a6-8654-22277ff1be16">

**Comment by Ayush398** [comment]
Please assign me this issue

**Comment by rithviknishad** [comment]
@Ayush398 feel free to take up once PR for #294 is made

**Comment by rash-27** [comment]
If anyone is not working on this issue , I would like to work on this

**Comment by kumar11jr** [comment]
please assign me this issue @rithviknishad .
i would love to work on this

**Comment by rithviknishad** [comment]
yup. Also `justify-center` in mobile view

**Comment by rash-27** [comment]
okk
