### ISSUE TITLE
Migrate `fetchGitHubReleases` method to use `octokit` instead of using fetch to interact with GitHub APIs

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#347]
https://github.com/coronasafe/leaderboard/blob/main/app/api/leaderboard/functions.ts#L65

**Comment by dgparmar14** [comment]
**After solving feed page exception problem I am familiar with octokit documentation problem so i want take all of 3 issues. Issues number 
#345 #346 #347**

**Comment by rithviknishad** [comment]
@dgparmar14 you've 3 assigned issues with no PR already. Will assign the others once currently assigned ones are completed.

https://github.com/coronasafe/leaderboard/issues?q=assignee%3Adgparmar14+is%3Aopen+sort%3Aupdated-desc

**Comment by dgparmar14** [comment]
Okay sure, My exam is on going so I am not able to contribute with that much accuracy.  I will solve it all issues soon .

**Comment by manu-r12** [comment]
on my way🫡👨🏻‍💻
