### ISSUE TITLE
Configurable `favicon.ico` and `logo.webp`

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#352]
Multiple organizations could deploy leaderboards, so they'd need to personalize the deployment with their logo and icon.

Currently the `favicon.ico` is not configurable, and `logo.webp` is configurable via an env. 
However, since we keep organization-specific files in the data repo (eg: https://github.com/coronasafe/leaderboard-data/tree/main/config) let's keep this also in the data repo.

### Tasks

- [ ] Move `favicon.ico` and `logo.webp` to the data-repo (under the directory: `config/assets/...`) and replace the current `favicon.ico` and `logo.webp` in this repo with a symbolic link pointing to the favicon inside the data-repo.

**Comment by dgparmar14** [comment]
I previously solved some issues according to data-repo so I am familiar with symlinks and all workflow and I raised also 2 PRs Now can you assign this issue to me?

**Comment by kumar11jr** [comment]
can i work on this issue @rithviknishad .

**Comment by kumar11jr** [comment]
please assign me this issue @rithviknishad
