### ISSUE TITLE
Enhance Release Event Card for Mobile View

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#358]
https://contributors.ohc.network/releases

<img width="382" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/1b07fdc0-4ab0-480d-8c8c-5e4089628135">

**Comment by rash-27** [comment]
I would like to work on this issue

**Comment by rash-27** [comment]
is this ok when the screen size is small ?
![image](https://github.com/coronasafe/leaderboard/assets/146672184/53dda5fe-c97d-4b65-ac4d-cbae1a39b4a0)

**Comment by rithviknishad** [comment]
maybe we could make the font sizes smaller in mobile view. also decrease the amount of margin so that we get more width to play around.

We could also hide the "coronasafe" / github org. part in mobile view.

**Comment by rash-27** [comment]
okk

**Comment by rithviknishad** [comment]
Also, we are showing the release time on the home page but not on the dedicated release section. Can we add that too on this page?
<img width="898" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/12d92ef6-75b7-4d75-bcff-00640cdf3e3d">

**Comment by rash-27** [comment]
yes , I will update that too
