### ISSUE TITLE
background color of navbar causes issues with readability

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#359]
In certain cases, when the content behind the navbar has white color, the navbar contents are not readable.

<img width="453" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/b0dab967-ef85-4611-8b27-d00a110e6335">

**Comment by rash-27** [comment]
i would like to work on this issue

**Comment by rash-27** [comment]
For increasing readability , we can fix the color of the navbar with the background color , how does that sound ?

**Comment by rithviknishad** [comment]
yup! we could try that

**Comment by rash-27** [comment]
okk
