### ISSUE TITLE
Home page's leaderboard title is statically typed

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#36]
https://github.com/coronasafe/leaderboard/blob/c0d90ddcf93a3d56b759f0ecd4afdc690f3dcadb/pages/index.js#L76

![image](https://user-images.githubusercontent.com/25143503/171084350-10e5dede-210b-4ce4-8383-37262f20ffd2.png)

**Comment by bodhish** [comment]
It's Tuesday to Monday
