### ISSUE TITLE
Sidebar misaligned and unable to close the sidebar in mobile view when in Projects page

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#360]
### Action Items

- [ ] Fix misaligned sidebar issue in mobile view for projects page
- [ ] Auto-close sidebar when a link is clicked in mobile view

https://contributors.ohc.network/projects

<img width="393" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/f023a5de-a0e0-4051-b1f1-8639b62dc53b">

**Comment by kumar11jr** [comment]
Hii @rithviknishad  can you please assign me this issue
