### ISSUE TITLE
Broken responsiveness for Active Projects page in mobile view

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#361]
https://contributors.ohc.network/projects

<img width="396" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/50de7d91-e4be-4c81-8644-5f872394b1d6">

**Comment by itxsoumya** [comment]
i would like to work on this issue

**Comment by itxsoumya** [comment]
@rithviknishad There are two things that we can do.
* Wrap them one after another for mobile devices 
or
* replace `google summer of code` with `gsoc` or `gsoc icon` and `open with github` with github icon for mobile devices.

Which one do you prefer ?

**Comment by rithviknishad** [comment]
Yup, we can wrap them plus we could just show "GSoC" by removing the custom mapping table that maps the github issue labels to texts. 

GSoC icon would be nice to have, but think of this feature being used by multiple organizations. Some may not have GSoC configured in their active projects for their org, some would. Eventually, these pieces should be configurable across deployments. So hard-coding an icon wouldn't be nice.
