### ISSUE TITLE
Change review event text in GitHub Feed

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#362]
`{reviewer} {review event} {repo name} { pr number }` doesn't sound right.
Instead show: `{reviewer} {review event} { pr number } in {repo name}`

<img width="867" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/7cb7a15a-34db-4244-875f-4ad6c525996e">

**Comment by rash-27** [comment]
i would like to work on this issue
