### ISSUE TITLE
Leaderboard filters occupying so much space in mobile view

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#363]
### Action Items
- [ ] Make the filters collapsible in mobile view or move "Role" and "Sorting" filters to secondary filters inside a popover which can be viewed upon pressing a button.
- [ ] Reduce the font-size in mobile view

<img width="390" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/e81daffe-a1e6-4abb-8b59-0c3ecdb269e0">

**Comment by kshitijv256** [comment]
I would like to work on this issue
