### ISSUE TITLE
Add `View All` option in leaderboard filter

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/leaderboard#395]
Add `View All` option in the leaderboard filter so that all activity is displayed

![image](https://github.com/coronasafe/leaderboard/assets/70687348/79acd63d-4add-4582-8293-afe9d537dc41)

**Comment by Pranshu1902** [comment]
@rithviknishad @khavinshankar what are your thoughts on this?

**Comment by rithviknishad** [comment]
Duplicate of https://github.com/coronasafe/leaderboard/issues/294

Feel free to re-open the issue if something else was intended 😄
