### ISSUE TITLE
Top contributors card automatically takes first element even when no contribution.

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#40]
**Steps to reproduce:** 
- Use deployment with Leaderboard history feature #37
- Navigate to week with no contribution (eg. week-10: https://leaderboard-a9k47l53b-coronasafe.vercel.app/leaderboard/10)

**Expected Result:** 
- Top Contributor Card should not show the contributor if categories activity is 0.
- Leaderboard list: filter contributors with 0 activity.

![image](https://user-images.githubusercontent.com/25143503/171177234-085d36e6-4f43-4af6-b918-316e7965dc4b.png)

**Comment by Ritesh-Aggarwal** [comment]
Any suggestions on what should be shown when no data is available? @bodhish

**Comment by bodhish** [comment]
Hide the card 😅

**Comment by Ritesh-Aggarwal** [comment]
fixed in PR : #37
