### ISSUE TITLE
The footer is showing no image 

### ISSUE THREAD

**Issue by AshrafMd-1** [coronasafe/leaderboard#403]
On the leaderboard website when you scroll down to the footer page the image is not being rendered

![image](https://github.com/coronasafe/leaderboard/assets/98876115/24aa8acd-e5bc-4d85-8e13-7c923f58ec4f)

**Comment by AshrafMd-1** [comment]
@rithviknishad i want to work on this issue can you assign me this

**Comment by AshrafMd-1** [comment]
@rithviknishad once can you check the deployment 
because locally its getting displayed locally

**Comment by dgparmar14** [comment]
@rithviknishad I already fixed in my pr #396 .

**Comment by AshrafMd-1** [comment]
As this issue is already fixed I am gonna close this Issue
