### ISSUE TITLE
Footer doesn't respect the theme.

### ISSUE THREAD

**Issue by bodhish** [coronasafe/leaderboard#411]
1. the logo does't show up
2. The light mode switch is not respected

<img width="1540" alt="image" src="https://github.com/coronasafe/leaderboard/assets/14979190/5192234c-17fe-42c9-b91c-7f5ca4413cf8">

**Comment by rithviknishad** [comment]
The logo issue has been solved in #404

**Comment by rash-27** [comment]
I would like to work on this issue
