### ISSUE TITLE
Lets skill the scroll for activity

### ISSUE THREAD

**Issue by bodhish** [coronasafe/leaderboard#412]
It doesn't make sense for the activity to have a scroll; 
<img width="938" alt="image" src="https://github.com/coronasafe/leaderboard/assets/14979190/b61e04d1-624e-4fb3-ad46-8695f98d452d">

While at it; Rename it to "Activity" instead of "Learning Activity"

**Comment by kumar11jr** [comment]
hey @bodhish  can you asign me this

**Comment by kumar11jr** [comment]
hey @bodhish kindly review it
