### ISSUE TITLE
Support for multiple contributors to be listed in top contributors

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#42]
As of now the Top Contributor card supports only 1 person for each category. However, multiple contributors may be present with equal top score in each category. Hence they should also be listed inside the card.

![image](https://user-images.githubusercontent.com/25143503/171206115-ca5fa9aa-95c4-4369-8419-d023e2489e88.png)

**Comment by rabilrbl** [comment]
@rithviknishad Make sure to make them small for whoever comes below!
