### ISSUE TITLE
Optimizing /people route

### ISSUE THREAD

**Issue by Re-Dei** [coronasafe/leaderboard#421]
The /people route has become slow because of the new hover feature. Since hover feature is only required when hovered, implement a dynamic import strategy to solve this issue.
Docs: https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading

**Comment by Re-Dei** [comment]
I am busy for 2 weeks and will only be available to solve this issue after these 2 weeks. So anyone who is willing to solve this issue in these 2 weeks are welcome.

**Comment by rash-27** [comment]
- before using dynamic import 
![image](https://github.com/coronasafe/leaderboard/assets/146672184/c9e38bdd-d882-48f2-91cf-a72bd023e291)
- after using dynamic import 
![Screenshot from 2024-04-03 19-48-11](https://github.com/coronasafe/leaderboard/assets/146672184/fa0dfd6a-8f73-4458-b8b4-199e1108ebfd)
and the after using dynamic import we are getting more size than the current one

**Comment by Re-Dei** [comment]
@rash-27 i think you forgot to put the condition when to dynamically import

**Comment by Re-Dei** [comment]
@rithviknishad sorry for making a PR before getting assigned. Just happened to get some free time today.

**Comment by rash-27** [comment]
@Re-Dei what I thought is that currently we are rendering '/people' on the server side and showing cards using tailwind (using opacity so that we are fetching them while rendering on the server) ,and converting that to a client side component may take away the advantages of the SSR right ?

**Comment by Re-Dei** [comment]
@rash-27 only the hover card is being rendered client side in my PR. You can see to learn more.

**Comment by rash-27** [comment]
Sure , I'll look into it .
