### ISSUE TITLE
Page for new contributors to contribute to OHC

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#426]
Create a page to list out all issues across all repos. of the org with "good first issue" label that has not been assigned to anyone yet.

**Comment by dgparmar14** [comment]
I want to work on this issue please assign me.

**Comment by dgparmar14** [comment]
![image](https://github.com/coronasafe/leaderboard/assets/99136186/453f464c-ee55-46a3-8d7a-6bd6c238858b)

**Comment by Harshal141** [comment]
I can work on this feature. I am currently not working on any issue so you can assign it to me, or else you can assign me to another issue if this one is taken.

**Comment by dgparmar14** [comment]
> I can work on this feature. I am currently not working on any issue so you can assign it to me, or else you can assign me to another issue if this one is taken.

Half work already done.

**Comment by Harshal141** [comment]
Ok sure no problem
