### ISSUE TITLE
Search icon misaligned in leaderboard search bar

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#435]
### URL:

https://contributors.ohc.network/leaderboard

### Browser Name:

Chrome

### Browser Version:

124.0.6367.61

### Operating System:

Mac OS Sonama

### How to reproduce the issue:

Go to the leaderboard page and observe the search bar

<img width="515" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/b22640f2-f3a7-4fb7-8447-10a489f569ee">

**Comment by dgparmar14** [comment]
@rithviknishad Please assign this issue to me
