### ISSUE TITLE
Redesign Footer to Include More Information about the Organization

### ISSUE THREAD

**Issue by dgparmar14** [coronasafe/leaderboard#436]
## Description
Currently, the footer only displays the logo, which doesn't offer much information about the organization. Let's redesign the footer to provide more details.

#### Organization Logo
Continue displaying the organization's logo for brand recognition and visual appeal.

#### Data Repository Link
Direct link to the organization's data repository, where users can access datasets, resources, or related materials.

#### Flat Repository Explorer Link
Link to the flat repository explorer tool, allowing users to navigate and explore the organization's repositories efficiently.

#### Social Media Links
Links to the organization's social media profiles (e.g., Twitter, LinkedIn, GitHub) for users to stay updated and engaged.

#### Contact Information
Contact details such as email address or a contact form for users to reach out with inquiries .

#### Feedback Link
Github issue page link (Hardcoded) to get feedbacks (Link:- https://github.com/coronasafe/leaderboard/issues/new/choose)

**Comment by KKartikay-27** [comment]
I would like to work on this issue !!

**Comment by mayank1365** [comment]
@dgparmar14 please assign this issue to me

**Comment by androemeda** [comment]
@rithviknishad please assign this issue to me

**Comment by mayank1365** [comment]
Hi @rithviknishad,

Could you please provide guidance on what the "Flat Repository Explorer Link" refers to?

**Comment by rithviknishad** [comment]
Check-out https://flatgithub.com

You can keep it as an env. variable pointing to: https://flatgithub.com/coronasafe/leaderboard-data

**Comment by mayank1365** [comment]
Thanks, I’ll check it out.
