### ISSUE TITLE
Improving page title and description

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#465]
### Enter your suggestions in details:

<img width="736" alt="image" src="https://github.com/user-attachments/assets/c2af13b7-4978-4d25-8409-135554fc0116">

Let's set the profile page title to something similar to: `{name (not username)} | {org}` (eg: "Rithvik Nishad | Open Healthcare Network"). 

Ref: https://nextjs.org/docs/app/api-reference/functions/generate-metadata#template

A suggestive meta description for the page could be a summary of the activity made so far and the joining date.

Suggestive example: "Rithvik Nishad has opened 123 pull requests so far since June 2000 at Open Healthcare Network" (feel free to improve this).

**Comment by sachan13harshit** [comment]
@rithviknishad can you please assign this to me !

**Comment by sachan13harshit** [comment]
@rithviknishad can you please review my pr
