### ISSUE TITLE
Improve the Footer Design

### ISSUE THREAD

**Issue by ayush2743** [coronasafe/leaderboard#478]
### **Description:**
The current footer design lacks visual appeal and does not meet modern design standards. The goal of this issue is to enhance the footer by:

- Adding Icons: Incorporate icons for GitHub, YouTube, LinkedIn, and Contact Us.
- Modular Design: Redesign the footer to be modular, ensuring it adheres to industry standards for responsiveness and usability.

**Suggested Design**

![Screenshot 2024-08-05 175723](https://github.com/user-attachments/assets/2bbe2f38-3d47-4b95-af55-1981295652c1)

**Comment by ayush2743** [comment]
@rithviknishad I will be working on this issue 👍

**Comment by rithviknishad** [comment]
This looks great @ayush2743 ! Looking forward to it!
