### ISSUE TITLE
Inconsistent Icon in Discussion Section

### ISSUE THREAD

**Issue by Indrajeety993648** [coronasafe/leaderboard#483]
### URL:

http://localhost:3000/discussions

### Browser Name:

Brave

### Browser Version:

Version 1.66.113 Chromium: 125.0.6422.76 (Official Build) (64-bit)

### Operating System:

Linux

### How to reproduce the issue:

# Inconsistent Icon in Discussion Section

## Description
The GitHub icons in the repository are consistent across all sections except for the discussion section, which has a different icon. This inconsistency should be addressed to ensure uniformity across the platform.

## Steps to Reproduce
1. Navigate to the repository.
2. Observe the GitHub icons in different sections such as "Projects", "LeaderBoard", "feed", etc.
3. Go to the "Discussions" section.
4. Notice the different icon used in the "Discussions" section.

## Expected Behavior
The icon in the "Discussions" section should be consistent with the icons used in other sections of the repository.

### Incorrect Icon in Discussions Section
![Screenshot from 2024-08-08 11-27-30](https://github.com/user-attachments/assets/753c5521-2b9b-4ce6-b441-3eb7f6657ab0)

### Correct Icons in Other Sections
![Screenshot from 2024-08-08 11-27-38](https://github.com/user-attachments/assets/c80975bd-f7c9-40c3-8b06-db97b6660545)

## Additional Context
Consistency in UI elements helps in maintaining a professional look and improves user experience.

## Proposed Solution
Update the icon in the "Discussions" section to match the icons used in other sections of the repository.

**Comment by Indrajeety993648** [comment]
@rithviknishad   please Assign this issue to me .

**Comment by rithviknishad** [comment]
@Indrajeety993648 this is the expected icon as it matches the button's style. This is the same icon that's used in projects section and good first issues sections too. So it is not inconsistent.

Feel free to re-open the issue if there are any other related issue.
