### ISSUE TITLE
Recommend using Fine-grained Personal Access Tokens (Beta) for better security

### ISSUE THREAD

**Issue by HUN-sp** [coronasafe/leaderboard#488]
### Enter your suggestions in details:

Currently, the documentation suggests using a classic personal access token for running the development server when encountering the "GITHUB_PAT is not configured" error. However, it would be more secure and in line with best practices to recommend using Fine-grained Personal Access Tokens (Beta) instead.

Reasons for the change:

Fine-grained tokens offer more granular control over access permissions, allowing users to limit access to specific repositories and actions.
They enhance security by reducing the risk if the token is compromised.
Users can set an expiration date for these tokens, further minimizing potential security risks.

In the troubleshooting section, update the note to recommend fine-grained personal access tokens, and provide a link to the relevant GitHub documentation.

This update will help users adopt more secure practices when interacting with the GitHub API.
![image](https://github.com/user-attachments/assets/96c1fd3e-77c3-4398-b2f4-a6a865ed4bfa)

**Comment by HUN-sp** [comment]
@Ashesh3 I would update and resolve it. Please assign it to me.

**Comment by HUN-sp** [comment]
@rithviknishad Assign it to me

**Comment by rithviknishad** [comment]
@HUN-sp 

1. Both Fine-grained tokens and Tokens (classic) are valid GitHub PAT tokens.
2. You can interchange Fine-grained tokens and classic tokens for leaderboard builds as the permission scopes required for leaderboard are available on both.
3. I just generated a fine-grained token and successfully ran a build, and it works fine! No limitations on using fine-grained tokens directly, nor any code change required.

![image](https://github.com/user-attachments/assets/d1bf9185-ae62-4368-aa05-51e839bb5a03)


Closing this issue as not a valid request. Feel free to reopen if you meant something else.
