### ISSUE TITLE
Incomplete Prerequisite Instructions

### ISSUE THREAD

**Issue by abhinav26966** [coronasafe/leaderboard#495]
### Enter your suggestions in details:

The prerequisite section mentions ensuring that 'pnpm' is installed but doesn't provide the installation steps or direct instructions.

Solution : 

- Provide a brief instruction or link directly to the 'pnpm' installation steps.

**Comment by abhinav26966** [comment]
Hey @rithviknishad, I have a solution for this issue.
Can you please assign this issue to me.

**Comment by sainak** [comment]
@abhinav26966 pnpm is a popular package manager with good documentation, anyone can get to the installation instructions with a simple google search

**Comment by sainak** [comment]
resolved in https://github.com/coronasafe/leaderboard/pull/414

**Comment by abhinav26966** [comment]
ohh alright @sainak 
Thanks for the clarification.
