### ISSUE TITLE
Refactor: move boilerplate code from each page to _app.js

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/leaderboard#56]
Todo:
- [x] create a component for `Footer`
- [x] remove `Header`, `PageHead` and `Footer` from each page and move it into _app.js

**Comment by rithviknishad** [comment]
@khavinshankar footer component has been refactored in https://github.com/coronasafe/leaderboard/pull/52/files#diff-3ebccc91178536d06703a58be49b5077d0535c8ff3ab2512af21ca060c5b4e77

**Comment by khavinshankar** [comment]
@rithviknishad got it 👍 thanks for the headsup, I'll just push additional changes after that pr is merged
