### ISSUE TITLE
Critical Bug in search

### ISSUE THREAD

**Issue by rabilrbl** [coronasafe/leaderboard#75]
- As I type my name, I hold the "1" badge
- Under all categories in "Top Contributors of the week" my name appear.
![image](https://user-images.githubusercontent.com/63334479/187492261-09a47877-0b74-4b23-8830-396a2af2cf47.png)

**Comment by Ritesh-Aggarwal** [comment]
> * As I type my name, I hold the "1" badge


@rabilrbl , Should badge be removed ? I don't think having a badge in this case is a problem. What do you suggest ?

**Comment by rabilrbl** [comment]
I think its better to remove badge when filtering is active?
