### ISSUE TITLE
Capture contributions from other repos

### ISSUE THREAD

**Issue by gigincg** [coronasafe/leaderboard#79]
We need to capture contributions from the following repos as well
 - coronasafe/10bedicu
 - coronasafe/care_dashboard

**Comment by Ritesh-Aggarwal** [comment]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/57039447/188262603-14f9bd36-72c0-4d88-99cc-2d7189dd62e3.png">

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/57039447/188262672-83772464-fb65-4809-908d-6c829476715e.png">

<img width="722" alt="image" src="https://user-images.githubusercontent.com/57039447/188262686-72804bac-ba96-4a31-bd28-76cb7f0d5ea9.png">

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/57039447/188262717-624d4922-f992-479b-b6c6-43fbbb79be7c.png">


All repos in coronasafe are being tracked as current implementation tracks all events in coronasafe org regardless of repo.

@sainak is that right?

**Comment by sainak** [comment]
@Ritesh-Aggarwal yes thats the current behaviour.
