### ISSUE TITLE
Flaw in the way we are capturing collaboration event

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#93]
Lots of collaborated events registered due to following production release PRs in care.

- https://github.com/coronasafe/care_fe/pull/3736 (23 collab events for @rithviknishad )
- https://github.com/coronasafe/care_fe/pull/3689 (18 collab events for @rithviknishad )

cc: @khavinshankar 

https://user-images.githubusercontent.com/25143503/194924567-7e9c2df0-3b0e-47bf-9992-526e1ec06ac5.mp4

**Comment by khavinshankar** [comment]
Fixed in https://github.com/coronasafe/leaderboard/pull/94
